apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: socp-system
resources:
  - namespace.yaml
  - service-account.yaml
  - runtime-config.yaml
  - api-gateway.yaml
  - search-config.yaml
  - detect-web.yaml
  - alert-web.yaml
  - autoscaling.yaml
  - network-policies.yaml
  - slo-alerts.yaml
