ALTER TABLE t_detection_route_outbox
    ADD COLUMN sequence_no BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE t_detection_route_outbox
    ADD COLUMN processing_key VARCHAR(600);

MERGE INTO t_detection_route_outbox AS current_row
USING (
    SELECT delivery_id, ROW_NUMBER() OVER (ORDER BY created_at, delivery_id) AS ordered_sequence
    FROM t_detection_route_outbox
) AS ranked
ON current_row.delivery_id = ranked.delivery_id
WHEN MATCHED THEN UPDATE SET sequence_no = ranked.ordered_sequence;

MERGE INTO t_detection_route_outbox AS current_row
USING (
    SELECT delivery_id, tenant_id, routing_key,
           ROW_NUMBER() OVER (
               PARTITION BY tenant_id, routing_key ORDER BY sequence_no
           ) AS claim_rank
    FROM t_detection_route_outbox
    WHERE status = 'PROCESSING'
) AS claimed
ON current_row.delivery_id = claimed.delivery_id
WHEN MATCHED THEN UPDATE SET processing_key =
    CASE WHEN claimed.claim_rank = 1
         THEN claimed.tenant_id || ':' || claimed.routing_key
         ELSE NULL END;

CREATE UNIQUE INDEX ux_detection_route_processing_key
    ON t_detection_route_outbox (processing_key);

CREATE INDEX idx_detection_route_outbox_key_sequence
    ON t_detection_route_outbox (tenant_id, routing_key, sequence_no);
