-- Tenant-owned watchlists are shared by every Detection instance. A row is
-- either a values overlay or a tombstone hiding a packaged template.
CREATE TABLE IF NOT EXISTS t_watchlist (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   VARCHAR(64) NOT NULL,
    list_name   VARCHAR(255) NOT NULL,
    values_json TEXT NOT NULL,
    deleted     BOOLEAN NOT NULL DEFAULT FALSE,
    row_version BIGINT NOT NULL DEFAULT 0,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_watchlist_tenant_name
    ON t_watchlist (tenant_id, list_name);
CREATE INDEX IF NOT EXISTS idx_watchlist_tenant
    ON t_watchlist (tenant_id);
