socp:
  maturity: preview
  hips-collect:
    simulation-enabled: false

spring:
  datasource:
    url: ${SOCP_HIPS_COLLECT_DB_URL:}
    driver-class-name: org.postgresql.Driver
    username: ${SOCP_HIPS_COLLECT_DB_USERNAME:}
    password: ${SOCP_HIPS_COLLECT_DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
