-- detect-model 二次分析结果持久化（t_analyzed：研判记录重启不丢）
CREATE TABLE IF NOT EXISTS t_analyzed (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id   VARCHAR(64),
    rule_id    VARCHAR(128),
    rule_name  VARCHAR(256),
    severity   VARCHAR(16),
    message    VARCHAR(1024),
    entity     VARCHAR(256),
    ts         TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_t_analyzed_ts ON t_analyzed (ts DESC);
