-- Durable source-alarm claim prevents Kafka redelivery from re-evaluating
-- stateful rules or emitting a second logical analysis result.
CREATE TABLE IF NOT EXISTS t_analysis_receipt (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        VARCHAR(64)  NOT NULL,
    source_alarm_id  VARCHAR(128) NOT NULL,
    analyzer_version VARCHAR(128) NOT NULL,
    status           VARCHAR(32)  NOT NULL,
    claimed_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    completed_at     TIMESTAMP(6) WITH TIME ZONE,
    result_count     INTEGER,
    CONSTRAINT uq_analysis_receipt_key
        UNIQUE (tenant_id, source_alarm_id, analyzer_version)
);
CREATE INDEX IF NOT EXISTS idx_analysis_receipt_status
    ON t_analysis_receipt (status, claimed_at);
