-- soc-base 审计落库 schema（对应架构 §3：@AuditOperation → Kafka socp-audit → soc-base → PG/H2）
--
-- 由 Flyway 接管（spring.jpa.hibernate.ddl-auto=none）。
-- 兼容性约定（H2 2.x MODE=PostgreSQL 与 PostgreSQL 16+ 共用同一份 DDL）：
--   * 短文本一律 VARCHAR(n)（不用 CHAR，避免 PG 右填充空格）；
--   * java.time.Instant 在 Hibernate 6 里映射为 TIMESTAMP(6) WITH TIME ZONE；
--   * 全部 CREATE ... IF NOT EXISTS：配合 baseline-on-migrate=true，老库不冲突。

CREATE TABLE IF NOT EXISTS t_audit (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id  VARCHAR(64)  NOT NULL DEFAULT 'default',
    action     VARCHAR(128) NOT NULL,
    operator   VARCHAR(128) NOT NULL DEFAULT 'system',
    target     VARCHAR(512),
    result     VARCHAR(64)  NOT NULL DEFAULT 'OK',
    ts         TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_t_audit_tenant_ts ON t_audit (tenant_id, ts DESC);
CREATE INDEX IF NOT EXISTS idx_t_audit_action    ON t_audit (action);
