apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: socp-staging
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: search-config-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: search-config-worker
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: detect-web-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: detect-web-worker
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: alert-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
