import { computed } from 'vue'
import { useI18n } from './useI18n'

export function useIngestCopy() {
  const { t } = useI18n()
  return computed(() => ({
    platformDefault: t('ingestion.platformDefault'),
    replayWarning: t('ingestion.replayWarning'),
    noSource: t('ingestion.noSource'),
    requiredConnection: t('ingestion.requiredConnection'),
    validated: t('ingestion.validated'),
    firstSource: t('ingestion.firstSource'),
    firstHint: t('ingestion.firstHint'),
    observations: t('ingestion.observations'),
    debugHint: t('ingestion.debugHint'),
    debugForwarded: t('ingestion.debugForwarded'),
    receivedDebugFailed: t('ingestion.receivedDebugFailed'),
    setup: t('ingestion.setup'),
    sourceSearch: t('ingestion.sourceSearch'),
    sample: t('ingestion.sample'),
    example: t('ingestion.example'),
    previewHint: t('ingestion.previewHint'),
    builtins: t('ingestion.builtins'),
    outputHint: t('ingestion.outputHint'),
    localPath: t('ingestion.localPath'),
    brokers: t('ingestion.brokers'),
    kafkaHint: t('ingestion.kafkaHint'),
    draft: t('ingestion.draft'),
    event: t('ingestion.event'),
    repair: t('ingestion.repair'),
    tokenPreserve: t('ingestion.tokenPreserve'),
    tokenClear: t('ingestion.tokenClear'),
    validate: t('ingestion.validate'),
    metadata: t('ingestion.metadata'),
    scope: t('ingestion.scope'),
    scopeHint: t('ingestion.scopeHint'),
    pipelineHint: t('ingestion.pipelineHint'),
    disabledRule: t('ingestion.disabledRule'),
    bindFirst: t('ingestion.bindFirst'),
    bind: t('ingestion.bind'),
    bound: t('ingestion.bound'),
    connect: t('ingestion.connect'),
    preview: t('ingestion.preview'),
    destination: t('ingestion.destination'),
    apply: t('ingestion.apply'),
    verify: t('ingestion.verify'),
    saved: t('ingestion.saved'),
    enabled: t('ingestion.enabled'),
    disabled: t('ingestion.disabled'),
    appliedUnknown: t('ingestion.appliedUnknown'),
    version: t('ingestion.version'),
    reload: t('ingestion.reload'),
    edit: t('ingestion.edit'),
    external: t('ingestion.external'),
    externalBlocked: t('ingestion.externalBlocked'),
    collectorIdentity: t('ingestion.collectorIdentity'),
    runPreview: t('ingestion.runPreview'),
    previewSuccess: t('ingestion.previewSuccess'),
    pipeline: t('ingestion.pipeline'),
    noBindings: t('ingestion.noBindings'),
    parserNew: t('ingestion.parserNew'),
    noOutput: t('ingestion.noOutput'),
    manageOutputs: t('ingestion.manageOutputs'),
    render: t('ingestion.render'),
    copy: t('ingestion.copy'),
    manualApply: t('ingestion.manualApply'),
    unsupportedRender: t('ingestion.unsupportedRender'),
    ack: t('ingestion.ack'),
    verifyHint: t('ingestion.verifyHint'),
    checkEvent: t('ingestion.checkEvent'),
    notObserved: t('ingestion.notObserved'),
    verified: t('ingestion.verified'),
    degraded: t('ingestion.degraded'),
    firstEventHint: t('ingestion.firstEventHint'),
    checking: t('ingestion.checking'),
    previewVersion: t('ingestion.previewVersion'),
    missingRule: t('ingestion.missingRule'),
    error: t('ingestion.error'),
    outputWarning: t('ingestion.outputWarning'),
    rendered: t('ingestion.rendered'),
    copied: t('ingestion.copied'),
    outputEnabled: t('ingestion.outputEnabled'),
    outputDisabled: t('ingestion.outputDisabled'),
  }))
}
