-- STIX 2.1/TAXII metadata is additive; old local IOC rows remain valid.
ALTER TABLE t_ioc ADD COLUMN IF NOT EXISTS feed VARCHAR(256);
ALTER TABLE t_ioc ADD COLUMN IF NOT EXISTS external_id VARCHAR(512);
ALTER TABLE t_ioc ADD COLUMN IF NOT EXISTS confidence DOUBLE PRECISION;
ALTER TABLE t_ioc ADD COLUMN IF NOT EXISTS tlp VARCHAR(32);
ALTER TABLE t_ioc ADD COLUMN IF NOT EXISTS valid_from TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE t_ioc ADD COLUMN IF NOT EXISTS valid_until TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE t_ioc ADD COLUMN IF NOT EXISTS expiration TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE t_ioc ADD COLUMN IF NOT EXISTS revoked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE t_ioc ADD COLUMN IF NOT EXISTS provenance VARCHAR(128);
CREATE UNIQUE INDEX IF NOT EXISTS uk_t_ioc_tenant_feed_external
    ON t_ioc (tenant_id, source, external_id);
