ALTER TABLE t_ingestion_outbox
    ADD COLUMN sequence_no BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE t_ingestion_outbox
    ADD COLUMN processing_key VARCHAR(600);

-- Adding an identity fills legacy rows in physical scan order, which is not a
-- durable enqueue order after VACUUM/table rewrites. Preserve the publisher's
-- former created_at ordering for upgrades; the identity generator remains
-- above the populated row count for subsequently inserted records.
MERGE INTO t_ingestion_outbox AS current_row
USING (
    SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS ordered_sequence
    FROM t_ingestion_outbox
) AS ranked
ON current_row.id = ranked.id
WHEN MATCHED THEN UPDATE SET sequence_no = ranked.ordered_sequence;

-- Backfill only one visible legacy PROCESSING owner per key. Any duplicate
-- legacy claims stay visible with a null lease key, block new claims through
-- the predecessor query, and are cleared by normal stale-claim recovery.
MERGE INTO t_ingestion_outbox AS current_row
USING (
    SELECT id, tenant_id, routing_key,
           ROW_NUMBER() OVER (
               PARTITION BY tenant_id, routing_key ORDER BY sequence_no
           ) AS claim_rank
    FROM t_ingestion_outbox
    WHERE status = 'PROCESSING'
) AS claimed
ON current_row.id = claimed.id
WHEN MATCHED THEN UPDATE SET processing_key =
    CASE WHEN claimed.claim_rank = 1
         THEN claimed.tenant_id || ':' || claimed.routing_key
         ELSE NULL END;

CREATE UNIQUE INDEX ux_ingestion_outbox_processing_key
    ON t_ingestion_outbox (processing_key);

CREATE INDEX idx_ingestion_outbox_key_sequence
    ON t_ingestion_outbox (tenant_id, routing_key, sequence_no);

ALTER TABLE t_log_source
    ADD COLUMN ignore_older_seconds INTEGER;
