-- Tenant-owned configuration replaces or hides packaged catalog templates.
-- One row is either an overlay payload or a tombstone for the tenant/item.
CREATE TABLE IF NOT EXISTS t_tenant_catalog_entry (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_type VARCHAR(64) NOT NULL,
    tenant_id    VARCHAR(64) NOT NULL,
    item_id      VARCHAR(255) NOT NULL,
    payload      TEXT NOT NULL,
    deleted      BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_tenant_catalog_entry
    ON t_tenant_catalog_entry (catalog_type, tenant_id, item_id);
CREATE INDEX IF NOT EXISTS idx_tenant_catalog_entry_tenant
    ON t_tenant_catalog_entry (tenant_id, catalog_type);
