spring:
  flyway:
    url: jdbc:postgresql://${SOCP_PG_HOST:localhost}:${SOCP_PG_PORT:5432}/incident
    user: ${SOCP_PG_MIGRATION_USER:${SOCP_PG_USER:socp}}
    password: ${SOCP_PG_MIGRATION_PASSWORD:${SOCP_PG_PASSWORD:socp}}
