package com.socp.soar.web.domain;

public enum SoarRunStatus {
    QUEUED, DISPATCHING, RUNNING, WAITING_APPROVAL, WAITING_INPUT, CANCELLING,
    SUCCEEDED, PARTIALLY_SUCCEEDED, FAILED, TIMED_OUT, ACTION_UNKNOWN, CANCELLED,
    SUPPRESSED, DEAD
}
